import CustomNavbar from "./Navbar";

function About(){
  return(
    <div>
      <header>
        <CustomNavbar/>
      </header>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris facilisis dapibus auctor. Pellentesque volutpat non enim dictum hendrerit. Praesent bibendum semper placerat. Vivamus accumsan iaculis augue, egestas pulvinar sem ornare non. Suspendisse efficitur accumsan purus a porta. Ut tempor gravida ipsum sit amet elementum. Ut maximus ante sit amet fermentum feugiat. Sed luctus suscipit sollicitudin. Suspendisse feugiat mauris enim, ac molestie elit lobortis sed. Integer lectus est, faucibus quis justo quis, vestibulum finibus elit. Mauris vel pharetra nibh, eget aliquet magna. Aliquam diam enim, vulputate eu pulvinar quis, finibus quis nisl. Mauris cursus, nibh in lacinia fringilla, ante sapien pharetra ante, vel aliquam elit quam eget orci. Vestibulum semper eleifend urna, eget tincidunt libero sollicitudin eget. Etiam dignissim nec ex ut scelerisque. Vivamus tincidunt massa ac nisi ullamcorper tincidunt.

Fusce ultrices leo quis egestas vehicula. Maecenas urna nibh, pellentesque at ultrices in, hendrerit non sem. Donec at tellus vel sapien gravida auctor eget vel erat. Sed maximus bibendum lacus, eget dignissim nulla faucibus et. Ut quis hendrerit lorem. Sed pharetra lorem auctor quam malesuada mollis. Suspendisse volutpat neque vel diam blandit, vel feugiat lacus laoreet. Etiam gravida neque ipsum, et viverra tellus ultrices id. Nam efficitur mauris in eros semper, sed finibus enim vehicula. Sed et pretium quam.

Aliquam ac magna tortor. In vitae euismod massa, in lacinia erat. Praesent purus odio, tincidunt quis purus facilisis, consequat euismod velit. Vivamus dui nisi, iaculis in fermentum eget, maximus nec risus. Vestibulum ut dapibus augue. Vestibulum eu augue tincidunt, tristique metus eget, semper odio. Suspendisse felis nisl, euismod a ante quis, consectetur consequat dolor. Nullam mollis, mauris sit amet volutpat pulvinar, ex risus malesuada ligula, id aliquet magna enim at massa. Vivamus feugiat lectus id rutrum facilisis. Donec leo ante, bibendum id sapien ac, dictum accumsan justo. Cras eget metus vehicula, pellentesque erat ultrices, elementum lectus.

Suspendisse sed nunc facilisis, tempor ipsum vel, feugiat leo. Nunc consectetur dictum dui, vel dapibus nisl luctus tincidunt. Nulla facilisi. Nunc sagittis fringilla enim in lacinia. Nunc lobortis justo neque, quis sodales lectus condimentum ac. Duis semper aliquam turpis. Praesent risus ante, egestas in ornare id, porttitor non eros. Proin vel suscipit nibh. Donec vitae lobortis nunc, sed aliquam quam. Ut dictum lacinia quam, quis dictum nibh porta vel. Sed vulputate pharetra nibh ut cursus. Morbi ex mi, consequat nec scelerisque at, consequat vitae lorem. Maecenas porttitor sed urna quis egestas. Vivamus ac vehicula leo. Donec luctus sollicitudin augue, quis fermentum leo convallis eu. Donec pretium luctus bibendum.

Donec elit justo, blandit quis justo sollicitudin, posuere varius elit. Mauris luctus orci orci, quis fermentum dui efficitur ut. Nunc fringilla euismod ligula, sit amet porttitor felis porttitor non. Nunc risus augue, placerat non ante id, pharetra auctor sem. Mauris vel ullamcorper felis. Nam vitae mi sit amet turpis egestas congue. Quisque rutrum gravida consequat. Quisque tristique in risus vel gravida. Vestibulum placerat venenatis pharetra.

Cras eu bibendum est. Mauris nec enim diam. Sed orci justo, commodo in felis fringilla, congue efficitur leo. Phasellus consectetur condimentum posuere. Morbi tempus massa porttitor, mattis mauris quis, ullamcorper augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Aenean laoreet turpis mauris, eu maximus neque euismod venenatis. Etiam vitae convallis eros. In a viverra neque, sit amet sodales ante. Aliquam quis sem mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Morbi suscipit tempus massa a dignissim. Aliquam facilisis a nisl in mollis. Donec vestibulum est in risus efficitur commodo. Quisque in metus vel felis eleifend dictum. Quisque consequat sed arcu condimentum pharetra. Aliquam pretium ipsum vitae augue porta, quis volutpat mauris maximus. Praesent a urna lectus. Aliquam erat volutpat. Ut vitae metus erat. Fusce sodales ut neque id vestibulum. Etiam a felis vel tellus ultricies tincidunt. Maecenas facilisis accumsan ligula in eleifend.

Praesent at congue urna. Integer porta turpis nec ultrices fermentum. Maecenas eget aliquet mi. Cras sagittis elit sed risus bibendum tristique. Donec vitae dolor sed eros feugiat scelerisque. In ut neque lobortis, egestas leo sit amet, porttitor nulla. Aenean a ex risus. Mauris tincidunt fringilla massa ornare hendrerit. Morbi risus nulla, volutpat at ante ut, lacinia accumsan augue. Nunc faucibus nulla vel purus ultrices pulvinar. Phasellus ut tortor eget lacus consequat malesuada quis nec quam. Etiam posuere odio augue, vel interdum augue hendrerit quis. Nam ullamcorper pellentesque arcu vitae tempus. Quisque finibus lacus et scelerisque iaculis. Aliquam et sollicitudin felis.

Donec in hendrerit quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis pulvinar purus sit amet dui laoreet, a sagittis risus imperdiet. Donec dui tellus, viverra ut commodo sed, cursus id justo. Integer lorem quam, semper in mauris quis, scelerisque condimentum elit. Vestibulum elementum pretium lacus ac tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu lacus ac ipsum posuere fringilla at non tortor. Ut sagittis dolor ac ornare lobortis. Suspendisse potenti. Praesent fringilla, nisl vel porttitor cursus, lacus ipsum pellentesque elit, ut fermentum velit ex vitae massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque sit amet mauris eu arcu feugiat placerat id et tortor. Pellentesque et velit a neque ultrices tempor.

Sed erat tortor, aliquet ut ante nec, bibendum elementum elit. Etiam facilisis commodo laoreet. Curabitur vitae imperdiet magna, ullamcorper scelerisque eros. Phasellus commodo sollicitudin odio quis auctor. In hac habitasse platea dictumst. Suspendisse tincidunt malesuada iaculis. In vestibulum urna quis tincidunt tempus. Integer vitae commodo nibh, eget rutrum purus. Nulla est quam, ullamcorper id arcu nec, vulputate scelerisque ex. Aliquam vel commodo sem. Nam lobortis interdum venenatis. Praesent sit amet posuere elit. Cras feugiat sollicitudin tempus. Nunc lacinia sapien in sapien dapibus, id volutpat lectus dictum. Mauris ut dolor est. Sed varius consectetur orci, in consectetur risus pretium at.

Suspendisse potenti. Phasellus ac massa sit amet nisi tincidunt cursus. Integer id enim a magna vulputate consectetur in eget quam. Sed luctus enim tristique mauris tempor, eu semper justo malesuada. Quisque ullamcorper luctus nisl, non maximus lectus vehicula ut. Mauris quis auctor augue, quis semper felis. Nullam ut tincidunt purus. Praesent fermentum libero dictum bibendum hendrerit. Nulla facilisi. Nulla faucibus lectus vitae leo consequat efficitur.

Quisque vitae interdum ex. Etiam feugiat semper elit, sed maximus eros scelerisque iaculis. Cras ultricies orci sed ligula pulvinar pharetra. Pellentesque ut interdum nunc. Ut dignissim turpis id sem condimentum feugiat. Sed risus eros, vulputate eget nisi eget, scelerisque porta metus. Duis ut auctor lectus. Pellentesque erat lectus, posuere a lorem in, tincidunt aliquet mauris. Morbi id nunc non ligula lacinia dapibus. Donec rhoncus elit convallis, posuere libero nec, feugiat velit. Nullam varius, lectus sed mollis pharetra, lorem sem fermentum leo, vel ultrices mauris leo sed sem.

Etiam ornare ut sapien et gravida. Vestibulum et quam eget mi blandit aliquam non in felis. Nullam felis neque, tempor ac neque a, maximus tempor purus. Suspendisse tincidunt venenatis lacus ut venenatis. Ut egestas urna lacinia, elementum nulla et, varius dui. Quisque imperdiet varius mollis. Duis vestibulum sapien eget iaculis semper. Quisque non tortor gravida, placerat lorem eu, maximus odio. Suspendisse nunc dui, fringilla eget sagittis a, faucibus vitae purus. Fusce condimentum gravida risus ut vulputate. Morbi vel aliquam nisl. Nullam facilisis sodales quam pretium volutpat. Praesent facilisis dapibus sem. Etiam quam orci, pellentesque facilisis mauris sit amet, mattis malesuada ante. Fusce bibendum ligula ac egestas feugiat. In maximus ac massa vitae mollis.

Etiam molestie interdum justo eu venenatis. Morbi aliquam auctor ligula, at volutpat arcu blandit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean vel posuere nunc. Donec dapibus ornare lacus imperdiet viverra. Nullam a ex vulputate, pretium risus at, vulputate enim. Donec felis nisl, mollis eget molestie in, hendrerit id neque. Cras mauris dui, porta vitae sollicitudin non, cursus a ex. Sed id mauris id ipsum faucibus feugiat. Aliquam tempus venenatis risus, ac finibus libero consectetur eu. Nam vestibulum non neque nec tempor. Curabitur ac blandit nunc. Etiam suscipit porta neque, bibendum suscipit ante tempor vel.

Proin ac consectetur tellus. Donec condimentum faucibus sapien, vel congue diam tristique id. Integer non vulputate quam. Curabitur id fermentum tellus. Nunc est magna, mollis sed mauris a, suscipit convallis tortor. Duis eget lectus nec eros dictum porta dignissim id dolor. Mauris ultricies ornare leo, ac molestie nunc volutpat et. Sed elementum felis iaculis, fringilla mauris ut, tempor est. Cras at ex finibus, lacinia augue a, fringilla felis. Sed sed ligula id tortor tempus dictum at ac lorem. Cras quis pretium elit, eu feugiat magna. Phasellus tincidunt a ex non lobortis. Duis fringilla interdum arcu vitae placerat.

Nullam vitae tempus felis. Morbi tincidunt vel velit vitae facilisis. Suspendisse vitae hendrerit neque. Nullam pharetra a erat et sodales. Quisque bibendum enim sit amet nunc viverra luctus nec a leo. Mauris et velit nisl. Proin vel ligula sed risus blandit efficitur sit amet sit amet diam. Proin dapibus tincidunt ligula, a pellentesque mauris varius sit amet. Pellentesque consectetur velit non faucibus molestie. Fusce vel nulla ullamcorper, condimentum leo vel, ultricies libero. Nulla mattis purus sed ultricies luctus. Praesent suscipit faucibus quam in congue. Nam vulputate molestie elit ac mollis. Donec sed pulvinar turpis. Cras a tellus id felis pellentesque consequat. Nullam vitae augue commodo, varius felis id, interdum libero.

Nullam ante nisi, vulputate blandit blandit sit amet, elementum nec diam. Nam ac cursus libero, ac mollis erat. Phasellus elementum euismod dui, eget venenatis nulla efficitur feugiat. Duis sit amet libero tincidunt arcu euismod pretium. Aenean molestie metus molestie libero lacinia, id condimentum tortor sodales. Etiam et risus ac urna tempor condimentum. Vestibulum vitae odio non enim fermentum tincidunt. Morbi leo ligula, pulvinar ac pulvinar non, sollicitudin eget lorem. Praesent ultricies mattis semper. Fusce vitae blandit nulla. In egestas, enim eu cursus semper, nulla nibh elementum ligula, nec sagittis quam diam a sapien. Curabitur vitae ex ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elit nulla, sagittis rhoncus sapien non, dignissim molestie diam.

Phasellus rhoncus semper orci, ac condimentum odio iaculis sed. Etiam sagittis condimentum auctor. Phasellus nisi turpis, tincidunt sed pretium eget, efficitur sit amet lectus. Donec id dictum lectus. Nulla sit amet enim velit. Sed fringilla tristique diam id elementum. Suspendisse eu eleifend tellus. Ut eu porttitor justo. Phasellus vitae venenatis arcu.

Pellentesque laoreet, lectus id faucibus convallis, justo dui volutpat odio, vitae venenatis ante eros non nibh. Phasellus libero elit, consectetur eget purus in, luctus volutpat mi. Morbi cursus tristique turpis in blandit. Donec at ex vestibulum, scelerisque diam vel, maximus turpis. Proin sed eleifend neque, dictum lacinia purus. Pellentesque consectetur mauris et risus porttitor, sed dapibus risus pretium. Aliquam et porta lorem. Mauris congue orci ac odio eleifend fringilla. Phasellus rhoncus vulputate metus in vehicula. Aenean imperdiet maximus quam, quis consectetur dolor molestie quis. Ut sed leo tempus libero vulputate rutrum vel vitae lacus. Mauris pharetra enim vel nulla elementum ultrices. Ut et nulla eget risus euismod gravida non eget erat.

Nunc scelerisque scelerisque ornare. Duis nec ante vitae nibh pharetra dignissim. Morbi venenatis risus eget sapien elementum condimentum. Nam dignissim porta mauris, a congue turpis consequat vitae. Morbi cursus iaculis turpis non luctus. Suspendisse non arcu imperdiet, rutrum est ut, semper leo. Donec in sem sed mauris cursus maximus. Integer faucibus dui quis nisl faucibus aliquet. Vivamus vitae consectetur erat. Aliquam euismod arcu ac ante congue, eget sodales nulla consectetur. In mattis purus id odio varius, quis iaculis dolor ornare. Phasellus blandit justo eu felis ultrices, sit amet finibus neque lobortis.
      </p>
    </div>
  );
}
export default About;